apiVersion: v1
kind: Service
metadata:
  name: ayuntamiento-mongo
  namespace: proyecto-final
spec:
  selector:
    app: ayuntamiento-repo-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080