apiVersion: apps/v1
kind: Deployment
metadata:
  name: ayuntamiento-repo-deployment
  namespace: proyecto-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ayuntamiento-repo-deployment
  template:
    metadata:
      labels:
        app: ayuntamiento-repo-deployment
    spec:
      containers:
      - name: ayuntamiento-repo-deployment
        image: javijg487/app-ayuntamiento-repo-mongo:latest
        ports:
        - containerPort: 8080