apiVersion: v1
kind: Service
metadata:
  name: mongo-ayuntamiento
  namespace: proyecto-final
spec:
  selector:
    app: ayuntamiento-mongo-deployment
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017