apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ayuntamiento-mongo
  namespace: proyecto-final
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
