apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ayuntamiento-mongo
  namespace: proyecto-final
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pv-ayuntamiento-mongo"
