apiVersion: v1
kind: Service
metadata:
  name: bicicletas-mongo
  namespace: proyecto-final
spec:
  selector:
    app: bicicletas-mongo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080