apiVersion: v1
kind: Service
metadata:
  name: autenticacion
  namespace: proyecto-final
spec:
  selector:
    app: autenticacion-api-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080