version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "SQLPolucion SQLBicicletas"
    ports:
      - "3306:3306"
