version: '3.8'

services:
  db_polucion:
    image: mysql
    container_name: mysql-container-polucion
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SQLPolucion
    ports:
      - "3306:3306"

  db_bicicletas:
    image: mysql
    container_name: mysql-container-bicicletas
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SQLBicicletas
    ports:
      - "3307:3306"