apiVersion: v1
kind: Service
metadata:
  name: ayuntamiento-service
  namespace: proyecto-final
spec:
  selector:
    app: ayuntamiento-api-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080