apiVersion: v1
kind: Service
metadata:
  name: ayuntamiento
  namespace: proyecto-final
spec:
  selector:
    app: ayuntamiento-api-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080