apiVersion: v1
kind: Service
metadata:
  name: bicicletas
  namespace: proyecto-final
spec:
  selector:
    app: bicicletas-api-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080