apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: proyecto-final
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: curlimages
            image: curlimages/curl:8.8.0
            command: ["/bin/sh", "-c", "curl -H \"Authorization: Bearer $TOKEN\" http://ayuntamiento/api/v1/aggregateData"]
            env:
            - name: TOKEN
              valueFrom:
                configMapKeyRef:
                  name: token-config
                  key: token