apiVersion: v1
kind: Service
metadata:
  name: bicicletas-mysql-service
  namespace: proyecto-final
spec:
  selector:
    app: bicicletas-mysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080