apiVersion: v1
kind: Service
metadata:
  name: mongo-polucion
  namespace: proyecto-final
spec:
  selector:
    app: polucion-mongo-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080