apiVersion: apps/v1
kind: Deployment
metadata:
  name: polucion-mongo-deployment
  namespace: proyecto-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polucion-mongo-deployment
  template:
    metadata:
      labels:
        app: polucion-mongo-deployment
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/polucion-db-mongo
          name: mongo-storage
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: pvc-polucion-mongo
