apiVersion: v1
kind: Service
metadata:
  name: mongo-polucion
  namespace: proyecto-final
spec:
  selector:
    app: polucion-mongo-db-deployment
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017