apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bicicletas-bd-mysql
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/bicicletas-bd-mysql"
