apiVersion: apps/v1
kind: Deployment
metadata:
  name: bicicletas-bd-mysql
  namespace: proyecto-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bicicletas-bd-mysql
  template:
    metadata:
      labels:
        app: bicicletas-bd-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: SQLBicicletas
        volumeMounts:
        - mountPath: /var/lib/db-mysql
          name: mysql-storage
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: pvc-bicicletas-bd-sql
