apiVersion: v1
kind: Service
metadata:
  name: bicicletas-db-mongo-svc
  namespace: proyecto-conjunto
spec:
  selector:
    app: bicicletas-bd-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
