apiVersion: v1
kind: Service
metadata:
  name: mongo-bicicletas
  namespace: proyecto-final
spec:
  selector:
    app: bicicletas-bd-mongo-deployment
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
