apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bicicletas-bd-mongo
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/bicicletas-bd-mongo"
