apiVersion: apps/v1
kind: Deployment
metadata:
  name: bicicletas-bd-mongo-deployment
  namespace: proyecto-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bicicletas-bd-mongo-deployment
  template:
    metadata:
      labels:
        app: bicicletas-bd-mongo-deployment
    spec:
      containers:
      - name: mongo
        image: mongo:4.4
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db-mongo
          name: mongo-storage
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: pvc-bicicletas-bd-mongo
