apiVersion: v1
kind: Service
metadata:
  name: mysql-polucion
  namespace: proyecto-final
spec:
  selector:
    app: polucion-bd-mysql-deployment
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
