apiVersion: v1
kind: Service
metadata:
  name: polucion-sql
  namespace: proyecto-final
spec:
  selector:
    app: polucion-mysql-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080